management:
  endpoint:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: atomikos-demo
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    druid:
      userdb:
        name: userdb
        url: jdbc:mysql://192.168.99.100:3306/db_user
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: k12345678
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMills: 60000
        minEvictableIdleTimeMills: 30
        validationQuery: SELECT 1
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        useGloballDataSourceStat: true
      accountdb:
        name: accountdb
        url: jdbc:mysql://192.168.99.100:3306/db_account
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: k12345678
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMills: 60000
        minEvictableIdleTimeMills: 30
        validationQuery: SELECT 1
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        useGloballDataSourceStat: true

